name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read # Allow checkout

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Match requires-python in pyproject.toml

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff # Install ruff separately first
        pip install -e .[dev]
        # If no [dev] extra, install lint/test tools separately:
        # pip install -e .
        # pip install ruff pytest # Example tools

    - name: Debug Python Path
      run: python -c "import sys; print(sys.path)"

    - name: Lint with Ruff
      run: |
        ruff check . # Run ruff directly
        ruff format --check . # Run ruff directly

    - name: Test with pytest
      run: |
        pytest test_dir/

    - name: Build package
      run: python -m build 